baseURL: "https://jujumichl.github.io/todo/"
title: "Todo list"
theme: "hugo-blox"

enableGitInfo: true
defaultContentLanguage: fr
hasCJKLanguage: false

markup:
  goldmark:
    renderer:
      unsafe: true # pour autoriser HTML dans Markdown
