baseURL: "http://localhost:1313/"
title: "Suivi de projets"
theme: ["hugo-blox"]

enableGitInfo: true
defaultContentLanguage: fr
hasCJKLanguage: false

markup:
  goldmark:
    renderer:
      unsafe: true # pour autoriser HTML dans Markdown
