site_name: "Mon Site de Tâches & Documentation"
nav:
  - Accueil: index.md

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist       # pour les checkboxes fonctionnelles
  - pymdownx.details
  - admonition

extra_css:
  - assets/css/extra.css     # ton style personnalisé
